CREATE TABLE Employee 
(
    ID INT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    Prename VARCHAR(100) NOT NULL,
    CIN CHAR(8) UNIQUE NOT NULL,
    Email VARCHAR(150) NOT NULL,
    Phone_Number VARCHAR(255) NOT NULL,
    Home_Address VARCHAR(255) NOT NULL,
    Emp_Function VARCHAR(200) NOT NULL
);

CREATE TABLE Material (
	ID INT PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Price FLOAT NOT NULL,
	Purchase_Date DATE NOT NULL,
	Brand VARCHAR(100) NOT NULL,
	Reference VARCHAR(100) NOT NULL,
	IsTaken INT NOT NULL DEFAULT 0
);

CREATE TABLE Assign (
	ID INT PRIMARY KEY ,
	ID_Employee INT NOT NULL,
	ID_Material INT NOT NULL,
	Start_Date DATE NOT NULL,
	End_Date DATE NOT NULL,
	CONSTRAINT fk_idEmp FOREIGN KEY (ID_Employee) REFERENCES Employee(ID),
	CONSTRAINT fk_idMat FOREIGN KEY (ID_Material) REFERENCES Material(ID),
	
);
